import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { create } from '@react-three/test-renderer';
import { Matrix4, Color } from 'three';
import { Specimens } from '../src/assets-lab/AssetScene.jsx';
import { DOMAINS, PROFILES } from '../src/assets-lab/engine/config.js';
import { labRootPath } from '../src/assets-lab/engine/paths.js';
import { rootPaths, branchPaths } from '../src/assets-lab/engine/geometry.js';
global.IS_REACT_ACT_ENVIRONMENT=true;
const exporting=process.argv.includes('--export');
const report={date:new Date().toISOString(),browser:'Blocked by cloud browser URL security policy. No live browser, FPS, or physical iPhone result is claimed.',scenes:[],tests:[]};
await mkdir('.tmp/scenes',{recursive:true});
function inspect(scene){let calls=0,triangles=0,bytes=0,particles=0;const seen=new Set();scene.traverse(o=>{if(!o.isMesh&&!o.isPoints)return;const g=o.geometry;if(!g)return;for(const attr of Object.values(g.attributes)){for(const v of attr.array)assert.ok(Number.isFinite(v),'geometry contains non-finite coordinate');}const n=o.isInstancedMesh?o.count:1;if(o.isPoints)particles+=g.attributes.position.count;else triangles+=(g.index?g.index.count:g.attributes.position.count)/3*n;calls+=(o.material.transparent&&o.material.side===2&&!o.material.forceSinglePass?2:1);if(!seen.has(g.uuid)){seen.add(g.uuid);for(const a of Object.values(g.attributes))bytes+=a.array.byteLength;bytes+=g.index?.array.byteLength||0;}});return {drawCallsEstimate:calls,triangles:Math.round(triangles),geometryBytes:bytes,particles,uniqueGeometries:seen.size};}
function snapshot(scene){scene.updateMatrixWorld(true);const meshes=[];scene.traverse(o=>{if(!o.isMesh)return;const g=o.geometry,m=o.material;const geometry={attributes:Object.fromEntries(Object.entries(g.attributes).map(([k,v])=>[k,{array:Array.from(v.array),size:v.itemSize}])),index:g.index?Array.from(g.index.array):null};const material={color:m.color?.toArray()||[1,1,1],emissive:m.emissive?.toArray()||[0,0,0],emissiveIntensity:m.emissiveIntensity||0,metalness:m.metalness||0,roughness:m.roughness??.4,opacity:m.opacity??1,transparent:m.transparent,depthWrite:m.depthWrite,depthTest:m.depthTest,side:m.side,wireframe:m.wireframe,vertexShader:m.vertexShader,fragmentShader:m.fragmentShader,blending:m.blending,uniforms:m.uniforms?Object.fromEntries(Object.entries(m.uniforms).map(([k,u])=>[k,u.value?.toArray?u.value.toArray():u.value])):null};const count=o.isInstancedMesh?o.count:1;for(let i=0;i<count;i++){const matrix=new Matrix4();if(o.isInstancedMesh){o.getMatrixAt(i,matrix);matrix.premultiply(o.matrixWorld);}else matrix.copy(o.matrixWorld);const mat={...material};if(o.instanceColor){const c=new Color();o.getColorAt(i,c);mat.color=c.toArray();}meshes.push({geometry,material:mat,matrix:matrix.toArray()});}});return meshes;}
for(const [path,root] of [['/assets-lab','/'],['/assets-lab/','/'],['/NewStarrTree/assets-lab/','/NewStarrTree/'],['/NewStarrTree/','/NewStarrTree/']])assert.equal(labRootPath(path),root);report.tests.push('Root and GitHub Pages subpath asset URLs resolve with or without trailing slash');
assert.equal(branchPaths().length,18);assert.equal(new Set(branchPaths().map(p=>p.branch)).size,6);assert.equal(rootPaths().length,36);report.tests.push('Six distinct branch destinations and 36 deterministic root paths');
for(const profile of ['full','lite']) {
 const cases=[...['seed','network','terrain'].map(system=>({system,name:system})),{system:'seed',name:'seed-open',opened:true},...DOMAINS.map((d,i)=>({system:'ecosystem',selected:i,name:`domain-${d.id}`})),...Array.from({length:9},(_,i)=>({system:'journey',progress:i/8,name:`chapter-${i}`}))];
 for(const item of cases){const runtime={current:{time:4,pointer:{x:.18,y:.12},energy:.16}},events=[];const props={runtime,profile,growth:1,progress:.6,selected:0,opened:false,onSelect:i=>events.push(i),onActivate:()=>events.push('seed'),...item};const renderer=await create(<Specimens {...props}/>);if(item.opened)runtime.current.time=6.6;await renderer.advanceFrames(3,1/60);const scene=renderer.scene.instance;const metrics=inspect(scene);const budget=PROFILES[profile];assert.ok(metrics.triangles<budget.maxTriangles,`${profile}/${item.name}: ${metrics.triangles} triangles > ${budget.maxTriangles}`);assert.ok(metrics.drawCallsEstimate+8<=budget.maxDrawCalls,`${profile}/${item.name}: ${metrics.drawCallsEstimate+8} calls > ${budget.maxDrawCalls}`);report.scenes.push({profile,name:item.name,...metrics});
  if(item.system==='seed'){const clickable=renderer.scene.findAll(n=>!!n.props.onClick);assert.ok(clickable.length);await renderer.fireEvent(clickable[0],'click',{stopPropagation(){}});assert.ok(events.includes('seed'));const root=renderer.scene.findAll(n=>n.instance?.material?.uniforms?.uGrowth)[0];assert.equal(root.instance.material.uniforms.uGrowth.value,1);await renderer.update(<Specimens {...props} growth={.2}/>);await renderer.advanceFrames(1,1/60);const updatedRoot=renderer.scene.findAll(n=>n.instance?.material?.uniforms?.uGrowth)[0];assert.equal(updatedRoot.instance.material.uniforms.uGrowth.value,.2);report.tests.push(`${profile}/${item.name}: seed click fires activation; root shader responds to growth state`);await renderer.update(<Specimens {...props}/>);await renderer.advanceFrames(1,1/60);}
  if(item.system==='ecosystem'){renderer.scene.instance.updateMatrixWorld(true);const before=JSON.stringify(renderer.scene.instance.toJSON());runtime.current.time+=1;await renderer.advanceFrames(2,1/60);renderer.scene.instance.updateMatrixWorld(true);assert.ok(JSON.stringify(renderer.scene.instance.toJSON())!==before,'domain must respond to time');const clickable=renderer.scene.findAll(n=>!!n.props.onClick);await renderer.fireEvent(clickable[0],'click',{stopPropagation(){}});assert.ok(events.includes(item.selected));}
  if(exporting&&profile==='full'&&!item.name.startsWith('chapter'))await writeFile(`.tmp/scenes/${item.name}.json`,JSON.stringify(snapshot(scene)));
  await renderer.unmount();
 }
}
report.tests.push('All six domain objects route their own selection callbacks','All nine journey phases mount and advance in both profiles','All geometry has finite positions and stays within triangle/draw budgets (8 environment draws reserved)');
await writeFile('docs/assets-lab/verification.json',JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({passed:true,scenes:report.scenes.length,tests:report.tests,maxTriangles:Math.max(...report.scenes.map(s=>s.triangles)),maxEstimatedDraws:Math.max(...report.scenes.map(s=>s.drawCallsEstimate))+8},null,2));
