export const shellVertex = `varying vec3 vNormal; varying vec3 vView; varying vec3 vPosition;
void main(){vPosition=position; vec4 mv=modelViewMatrix*vec4(position,1.);vNormal=normalize(normalMatrix*normal);vView=normalize(-mv.xyz);gl_Position=projectionMatrix*mv;}`;
export const shellFragment = `uniform float uTime; uniform float uEnergy; uniform vec2 uPointer;
varying vec3 vNormal; varying vec3 vView; varying vec3 vPosition;
void main(){
 float fresnel=pow(1.-abs(dot(normalize(vNormal),normalize(vView))),2.3);
 float veins=pow(.5+.5*sin(atan(vPosition.z,vPosition.x)*6.+vPosition.y*1.4+uPointer.x*.6),18.);
 float flow=pow(.5+.5*sin(vPosition.y*5.-uTime*1.1),10.);
 vec3 shade=mix(vec3(.10,.21,.165),vec3(.82,.56,.22),fresnel);
 shade+=vec3(1.,.68,.28)*(veins*.5+flow*.07)*(.6+uEnergy);
 gl_FragColor=vec4(shade, .22+fresnel*.68+veins*.25);
}`;
export const rootVertex = `attribute float aBranch; attribute float aGrowth;
varying float vBranch; varying float vGrowth; varying vec3 vNormal;
void main(){vBranch=aBranch;vGrowth=aGrowth;vNormal=normalize(normalMatrix*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
export const rootFragment = `uniform float uTime;uniform float uGrowth;uniform float uSelected;uniform float uEnergy;uniform vec3 uColor;
varying float vBranch;varying float vGrowth;varying vec3 vNormal;
void main(){if(vGrowth>uGrowth) discard;
 float selectedPath=1.-step(.3,abs(vBranch-uSelected));
 float stream=pow(max(0.,sin(vGrowth*23.-uTime*2.8)),18.);
 float front=1.-smoothstep(0.,.06,abs(vGrowth-uGrowth));
 float light=.35+.65*max(0.,dot(normalize(vNormal),normalize(vec3(1.,1.,2.))));
 vec3 color=uColor*light*(.42+selectedPath*.65)+vec3(1.,.74,.35)*(stream*(.18+selectedPath*.85+uEnergy*.5)+front*.7);
 gl_FragColor=vec4(color,1.);}`;
export const dustVertex = `attribute float aSize;uniform float uTime;uniform float uDpr;varying float vAlpha;
void main(){vec3 p=position; p.y+=sin(uTime*.1+position.x)*.17;p.x+=sin(uTime*.08+position.z)*.12;
vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=min(7.,aSize*uDpr*27./-mv.z);vAlpha=.18+.35*pow(.5+.5*sin(uTime*.4+position.x*3.),2.);}`;
export const dustFragment = `varying float vAlpha;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;gl_FragColor=vec4(1.,.84,.57,(1.-smoothstep(.05,.5,d))*vAlpha);}`;
export const waterFragment = `uniform float uTime;varying vec2 vUv;
void main(){float streams=pow(.5+.5*sin(vUv.x*85.+sin(vUv.y*14.-uTime*2.)),4.);float fade=sin(vUv.x*3.14159)*smoothstep(0.,.14,vUv.y);float ripple=.5+.5*sin(vUv.y*55.+uTime*5.);gl_FragColor=vec4(mix(vec3(.18,.43,.38),vec3(.72,.91,.78),streams),fade*(.2+streams*.4+ripple*.12));}`;
export const uvVertex = `varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`;
